apiVersion: batch/v1beta1
kind: CronJob
metadata:
  creationTimestamp: null
  name: rbe-test-app-cron
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      creationTimestamp: null
    spec:
      backoffLimit: 0
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
          - command: ["/bin/sh", -c", "while true; do echo hello; sleep 10;done"]
            env:
            - name: TEST
              value: TOTO
            image: busybox
            imagePullPolicy: Always
            name: rbe-test-cron
            resources:
              limits:
                cpu: 200m
                memory: 800Mi
              requests:
                cpu: 50m
                memory: 50Mi
  schedule: 30 0 * * *
  successfulJobsHistoryLimit: 3
  suspend: false
